integrations:
  configurations:
    - type: first
      legalEntity: bank1
      config: "firstConfiguration"
    - type: first
      legalEntity: bank2
      config: "anotherFirstConfiguration"
    - type: second
      legalEntity: bank3
      config:
        url: "http://rcard.in/saymyname"